#!/bin/sh
set -eu

if [ "${1:-}" = "--nocgi" ]; then
  shift
fi

case "${1:-}" in
  init)
    destination=
    for argument in "$@"; do
      destination=$argument
    done
    if [ -z "$destination" ]; then
      exit 1
    fi
    printf '%s\n' 'fake fossil repository' > "$destination"
    ;;
  user|setting)
    ;;
  test-integrity)
    if [ "${FOSSILHUB_FAKE_INTEGRITY_FAIL:-0}" = "1" ]; then
      exit 1
    fi
    ;;
  cgi)
    printf '%s\r\n' 'Status: 200 OK'
    printf '%s\r\n' 'Content-Type: text/plain; charset=utf-8'
    printf '\r\n'
    printf 'fake public transport %s %s\n' \
      "${SCRIPT_NAME:-}" "${PATH_INFO:-}"
    ;;
  *)
    exit 1
    ;;
esac
